USE [ChangeLogSystem]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UpdateVersion](
	[UpdateId] [int] IDENTITY(1000,1) NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[Type] [varchar](50) NULL,
	[Content] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UpdateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO